name: Deploy PRD - PARA S3

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    - uses: dopplerhq/cli-action@v1
      with:
        node-version: 12.21.0
    - name: Set envs Agent GitHub Actions
      run: doppler secrets download --no-file --format=docker >> $GITHUB_ENV;
      env:
        DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN_PRD }}
    - name: Install AWS CLIENT
      run: pip install awscli
    - name: Install and Build
      run: npm install && npm run build
      env:
        CI: "false"
    - name: Deploy S#
      run: cd build && AWS_ACCESS_KEY_ID=${ACCESS_KEY} AWS_SECRET_ACCESS_KEY=${SECRET_KEY} aws s3 sync . s3://treinazap-daniel --acl public-read --delete
      env:
        ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
